from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Location(BaseModel):
    path: str
    start_line: Optional[int] = None
    end_line: Optional[int] = None


class Reachability(BaseModel):
    reachable: bool
    evidence: Optional[str] = None


class FindingStatusUpdate(BaseModel):
    status: str = Field(
        ..., description="The new status: 'open', 'accepted', or 'ignored'"
    )


class Finding(BaseModel):
    id: str = Field(
    ...,
    description="Unique identifier of the finding",
    examples=["F-001"]
)
    category: str = Field(
    ...,
    description="Category of the finding",
    examples=["SQL Injection"]
)
    severity: str = Field(
    ...,
    description="Severity level of the finding",
    examples=["High"]
)
    title: str = Field(
    ...,
    description="Short title of the finding",
    examples=["SQL Injection Vulnerability"]
)
    description: str = Field(
         default="",
         description="Detailed description of the finding"
     )
    location: Optional[Location] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    reachability: Optional[Reachability] = None
    features: Optional[Dict[str, Any]] = Field(default_factory=dict)
    ml_score: Optional[float] = None


class ScanResponse(BaseModel):
    job_id: str = Field(
        ...,
        description="Unique scan job identifier",
        examples=["job-123"]
    )
    project_name: str = Field(
        ...,
        description="Name of the scanned project",
        examples=["PatchPilot"]
    )
    repo_path: str = Field(
        ...,
        description="Path to the scanned repository",
        examples=["C:/Users/ADMIN/PatchPilot"]
    )
    findings: List[Finding] = Field(
        ...,
        description="List of findings generated by the scan"
    )
    scanners: Dict[str, Any] = Field(
        ...,
        description="Results produced by different scanners"
    )


class Fix(BaseModel):
    finding_id: str
    status: str
    summary: str
    files_changed: List[str] = Field(default_factory=list)
    diff: Optional[str] = None
    notes: List[str] = Field(default_factory=list)


class FixRequest(BaseModel):
    job_id: str
    finding_ids: List[str]


class FixResponse(BaseModel):
    job_id: str
    fixes: List[Fix]


class VerifyResponse(BaseModel):
    ok: bool
    checks: Dict[str, Any]


class OrgScanRequest(BaseModel):
    org_url: str


class RepoStatus(BaseModel):
    job_id: str
    project_name: str
    status: str


class OrgJobStatusResponse(BaseModel):
    org_job_id: str
    status: str
    repos: List[RepoStatus]
